"""empty message

Revision ID: 00548fe17319
Revises: 5f2145bac481
Create Date: 2019-10-08 16:51:40.153020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00548fe17319'
down_revision = '5f2145bac481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('city_name', sa.String(length=120), nullable=True))
    op.drop_column('cities', 'city')
    op.add_column('venues', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    op.add_column('cities', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('cities', 'city_name')
    # ### end Alembic commands ###
