"""empty message

Revision ID: 5f2145bac481
Revises: 8f692e6421e8
Create Date: 2019-10-08 15:03:19.288192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2145bac481'
down_revision = '8f692e6421e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venues', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venues', 'cities', ['city_id'], ['id'])
    op.drop_column('venues', 'city')
    op.drop_column('venues', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'city_id')
    op.drop_table('cities')
    # ### end Alembic commands ###
